storage:
  root_path: "data/"
  agency:
    path: "agency/"
    files:
      estate_ids: "estate_ids.txt"
      sqlite_db: "agency_data.db"
  wiki:
    path: "wiki/"
    files:
      pages: "wiki_data_partition_{num}.json"
  rag:
    path: "rag/"
    files:
      chroma_db: "chroma_db/"

cloud_storage:
  service_type: "cloudflare"

# Cloudflare R2 configuration
cloudflare:
  endpoint_url: "https://{account_id}.r2.cloudflarestorage.com"
  bucket_name: "hk-housing-datahub"
  region: "auto"
  datahub_folder_name: "data"

# AWS S3 configuration (use when service_type is "aws")
aws:
  bucket_name: "hk-housing-datahub"
  region: "us-east-1"

llm:
  ollama:
    default_model: "qwen3:8b"
